name: Obfuscation Job

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    paths:
      - '**'

jobs:
  obfuscate-powershell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run obfuscator script
      run: python utilitarian/obfuscator.py xps1.ps1 xps2.ps1

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref }}
        body: |
          obfuscated_weapons.cmd
          weapons.cmd
        draft: false
        prerelease: false

