name: Obfuscation Job

on:
  push:
    branches:
      - main
    paths:
      - xps1.ps1
      - xps2.ps1

jobs:
  obfuscate-powershell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run obfuscator script
      run: python utilitarian/obfuscator.py xps1.ps1 xps2.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: processed-files
        path: |
          obfuscated_weapons.cmd
          weapons.cmd
